"""Item/skill chairs' machinery: loaders + the stat-budget gate.

The **Item Director** owns ``games/<g>/items/`` (item@1), the skills the
Story/Systems chairs commission live in ``games/<g>/skills/`` (skill@1).
The stat-budget gate (studio-org ledger row 20) enforces the rulers in
``games/<g>/systems.md`` — the constants here MIRROR that document and
change only together with it.
"""
from __future__ import annotations

import json
from pathlib import Path

from automap.story import Finding

# rulers — mirror games/<g>/systems.md ("Stat budgets")
EQUIP_BUDGET_BASE = 1          # Σ|modifiers| ≤ tier + EQUIP_BUDGET_BASE
SKILL_ATK_MULT_CAP = 8.0
SKILL_STATUS_CAP = 60.0
SKILL_HITS_CAP = 4             # a flurry may split, never machine-gun
SKILL_TURNS_CAP = 5           # a status primes, never perma-locks
# typed-status magnitude ceilings (poison/regen/shield = HP, buffs = fraction)
STATUS_MAG_CAP = {"poison": 60.0, "regen": 40.0, "shield": 40.0,
                  "atk_up": 0.5, "atk_down": 0.5, "def_up": 0.5, "def_down": 0.5,
                  "stun": 0.0}
STATUS_KINDS = set(STATUS_MAG_CAP)
ANIM_KINDS = {"strike", "thrust", "bash", "cast", "bolt", "heal",
              "buff", "debuff", "self"}
EQUIPMENT_KINDS = ("weapon", "armor", "accessory")


def _load_dir(game_dir: Path, kind: str) -> dict[str, dict]:
    out: dict[str, dict] = {}
    d = game_dir / kind
    if d.exists():
        for p in sorted(d.glob("*.json")):
            out[p.stem] = json.loads(p.read_text())
    return out


def load_items(game_dir: Path) -> dict[str, dict]:
    return _load_dir(game_dir, "items")


def load_skills(game_dir: Path) -> dict[str, dict]:
    return _load_dir(game_dir, "skills")


def equip_budget(tier: int) -> int:
    return int(tier) + EQUIP_BUDGET_BASE


def check_items(game_dir: Path) -> list[Finding]:
    """The stat-budget gate over items. Errors block the publish."""
    findings: list[Finding] = []
    err = lambda who, msg: findings.append(Finding("error", who, msg))
    warn = lambda who, msg: findings.append(Finding("warn", who, msg))
    for iid, doc in load_items(game_dir).items():
        if doc.get("id") != iid:
            err(iid, f"file name and id disagree ({doc.get('id')!r})")
        kind = doc.get("kind", "")
        mods = doc.get("modifiers", {})
        if kind in EQUIPMENT_KINDS:
            tier = int(doc.get("tier", 1))
            spent = sum(abs(int(v)) for v in mods.values())
            budget = equip_budget(tier)
            if spent > budget:
                err(iid, f"modifiers spend {spent} > tier-{tier} budget "
                         f"{budget} (systems.md: Σ|modifiers| ≤ tier+1)")
            if spent == 0:
                warn(iid, "equipment with no modifiers — why equip it?")
        elif mods:
            err(iid, f"{kind!r} items carry no modifiers (equipment only)")
        if kind == "key" and doc.get("battle_usable"):
            err(iid, "key items are never battle_usable")
    return findings


def check_skills(game_dir: Path) -> list[Finding]:
    """The stat-budget gate over skills (formula caps)."""
    findings: list[Finding] = []
    err = lambda who, msg: findings.append(Finding("error", who, msg))
    for sid, doc in load_skills(game_dir).items():
        if doc.get("id") != sid:
            err(sid, f"file name and id disagree ({doc.get('id')!r})")
        formula = doc.get("formula", {})
        mult = float(formula.get("atk_mult", 6.0))
        if mult > SKILL_ATK_MULT_CAP:
            err(sid, f"atk_mult {mult} > cap {SKILL_ATK_MULT_CAP} "
                     "(systems.md: skills may exceed the basic attack, "
                     "never dwarf it)")
        status = doc.get("status", {})
        if status:
            kind = status.get("kind", status.get("id", ""))
            if kind not in STATUS_KINDS:
                err(sid, f"status kind {kind!r} not in {sorted(STATUS_KINDS)}")
            else:
                cap = STATUS_MAG_CAP[kind]
                if float(status.get("amount", 0)) > cap:
                    err(sid, f"status {kind} amount {status.get('amount')} > "
                             f"cap {cap} (a status primes, never perma-locks)")
            turns = int(status.get("turns", 0))
            if turns > SKILL_TURNS_CAP:
                err(sid, f"status turns {turns} > cap {SKILL_TURNS_CAP}")
        hits = int(doc.get("hits", 1))
        if hits > SKILL_HITS_CAP:
            err(sid, f"hits {hits} > cap {SKILL_HITS_CAP} "
                     "(a flurry may split, never machine-gun)")
        anim = doc.get("anim")
        if anim is not None and anim not in ANIM_KINDS:
            err(sid, f"anim {anim!r} not in {sorted(ANIM_KINDS)}")
    return findings


def library_md(game_dir: Path) -> str:
    """The item library — reuse-before-create, the asset library's sibling."""
    items = load_items(game_dir)
    skills = load_skills(game_dir)
    lines = ["# Item & skill library", "",
             "Generated by `16 items library`; the Item Director consults "
             "this BEFORE creating (dedup — ledger row 19).", "",
             "| item | kind | slot | tier | modifiers / use |", "|---|---|---|---|---|"]
    for iid, d in sorted(items.items()):
        detail = d.get("modifiers") or d.get("use") or {}
        lines.append(f"| {iid} | {d.get('kind')} | {d.get('slot', '—')} | "
                     f"{d.get('tier', 1)} | {json.dumps(detail)} |")
    lines += ["", "| skill | target | formula | status |", "|---|---|---|---|"]
    for sid, d in sorted(skills.items()):
        lines.append(f"| {sid} | {d.get('target_mode', 'enemy')} | "
                     f"{json.dumps(d.get('formula', {}))} | "
                     f"{json.dumps(d.get('status', {}))} |")
    return "\n".join(lines) + "\n"
