#!/usr/bin/env python
"""Stage 12 (game publish) - cascade generated game content into a game project.

The external-game twin of stage 7: Automap is the factory, the game project
(entropy-remade) is the consumer. Content sources live COMMITTED under
games/<game>/ (levels/creatures/dialogues as JSON — hand-transcribed for
fidelity or generated by the intake); binary assets (backgrounds, sprite
frames) are pulled from the reference repo per games/<game>/assets.json
(binaries never enter Automap's git; the game repo commits its own content).

    python scripts/12_publish_game.py --game entropy \
        [--game-dir ~/Cowork/entropy-remade]

Checks before anything moves:
- every JSON validates against its schema's newest version in platform-specs
  (levels -> level@*, creatures -> creature@*, dialogues -> dialogue-script@*);
  missing schema = warn (specs may lag during the campaign's early slices);
- the teleport graph is closed: a target_level that is not being published is
  an ERROR; a target spawn tag missing in the target level, or a level nothing
  teleports into, is a WARNING (the original game contains both — fidelity
  keeps them, loudly).

Publishing wipes each kind's directory first: the game's content tree is
always exactly what the pipeline last produced. A manifest.json records
artifacts + hashes for provenance and test pinning.
"""
from __future__ import annotations

import hashlib
import json
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

import typer

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

app = typer.Typer(add_completion=False)

JSON_KINDS = {"levels": "level", "creatures": "creature",
              "dialogues": "dialogue-script", "items": "item",
              "skills": "skill", "classes": "class"}
# kinds published by dedicated gated blocks (not the JSON_KINDS loop)
GATED_SCHEMAS = {"economy": "economy", "ui": "ui", "casting": None,
                 "cutscenes": "cutscene"}


def _validate(kind: str, path: Path, log) -> None:
    schema = JSON_KINDS.get(kind) or GATED_SCHEMAS.get(kind)
    if schema is None or path.suffix != ".json":
        return
    try:
        import platform_specs
    except ImportError:
        log(f"WARNING: platform-specs not installed - {path.name} NOT validated")
        return
    versions = sorted(
        (Path(platform_specs.__file__).parent.parent / "schemas" / schema).glob("*.json"))
    if not versions:
        log(f"WARNING: no {schema}@* schema yet - {path.name} published unvalidated")
        return
    platform_specs.validate(json.loads(path.read_text()), schema, versions[-1].stem)


def _check_teleport_graph(levels: dict[str, dict], log) -> list[str]:
    """Closed-graph check. Returns ERROR strings; warnings are logged."""
    errors: list[str] = []
    targeted: set[str] = set()
    for lid, doc in levels.items():
        for t in doc.get("teleports", []):
            target = t["target_level"]
            targeted.add(target)
            if target not in levels:
                errors.append(f"{lid}: teleport to unknown level '{target}'")
                continue
            tag = t.get("target_spawn_tag", "")
            if tag and tag not in {s["tag"] for s in levels[target]["spawns"]}:
                log(f"WARNING: {lid} -> {target} spawn tag '{tag}' missing in target "
                    "(player will use the target's direct-load position — original-game quirk)")
    for lid in levels:
        if lid not in targeted:
            log(f"WARNING: nothing teleports into '{lid}' (reachable only by direct load)")
    return errors


def _publish_dir_reset(dst: Path) -> None:
    if dst.exists():
        shutil.rmtree(dst)
    dst.mkdir(parents=True)


def _sha12(p: Path) -> str:
    return hashlib.sha256(p.read_bytes()).hexdigest()[:12]


@app.command()
def main(
    game: str = typer.Option("entropy", "--game", help="Game name under games/"),
    game_dir: Path = typer.Option(
        Path.home() / "Cowork" / "entropy-remade", "--game-dir",
        help="The consumer Godot project (has a content/ tree)"),
    root: Path = typer.Option(Path(__file__).resolve().parent.parent, "--root"),
):
    log = lambda m: typer.echo(f"[stage 12] {m}")
    src_root = root / "games" / game
    if not src_root.exists():
        raise typer.BadParameter(f"no content sources at {src_root}")
    if not (game_dir / "project.godot").exists():
        raise typer.BadParameter(f"{game_dir} is not a Godot project")
    content = game_dir / "content"
    manifest = {"game": game, "published_at": datetime.now(timezone.utc).isoformat(),
                "artifacts": {}}

    # --- JSON kinds: validate, graph-check levels, copy ---
    # source layout may be flat (<kind>/<id>.json) or foldered per scene
    # (<kind>/<id>/<id>.json, brief beside it) — published content stays
    # flat either way (copied by filename)
    def _json_files(src: Path) -> list[Path]:
        # flat, per-scene foldered, or regionally filed (<region>/<id>/)
        return sorted(list(src.glob("*.json")) + list(src.glob("*/*.json"))
                      + list(src.glob("*/*/*.json")))

    levels: dict[str, dict] = {}
    for kind in JSON_KINDS:
        src = src_root / kind
        if not src.exists():
            continue
        files = _json_files(src)
        for f in files:
            _validate(kind, f, log)
            if kind == "levels":
                doc = json.loads(f.read_text())
                if doc["id"] in levels:
                    log(f"ERROR: duplicate level id '{doc['id']}' "
                        f"({f}) — two source files claim it; delete one")
                    raise typer.Exit(code=1)
                levels[doc["id"]] = doc
        log(f"{kind}: {len(files)} valid")
    errors = _check_teleport_graph(levels, log)
    if errors:
        for e in errors:
            log(f"ERROR: {e}")
        raise typer.Exit(code=1)

    # --- casting sheets: the populate gate, then publish (studio-org row 10) ---
    casting_src = src_root / "casting"
    sheets = sorted(casting_src.glob("*.json")) if casting_src.exists() else []
    if sheets:
        from automap import casting as casting_mod
        blocked = False
        for f in sheets:
            sheet = json.loads(f.read_text())
            findings = casting_mod.check_sheet(src_root, sheet)
            for fd in findings:
                if fd.severity == "error":
                    log(f"ERROR: casting {f.name} [{fd.beat}]: {fd.message}")
                    blocked = True
                else:
                    log(f"casting {f.name} [{fd.beat}]: {fd.message}")
        if blocked:
            raise typer.Exit(code=1)
        dst = content / "casting"
        _publish_dir_reset(dst)
        for f in sheets:
            shutil.copy2(f, dst / f.name)
            manifest["artifacts"].setdefault("casting", []).append(
                {"name": f.name, "sha256_12": _sha12(f)})
        log(f"casting: {len(sheets)} sheet(s) gated + published")

    # --- gated game-shell kinds: items/skills budgets, economy sim,
    # ui readability (studio-org rows 20, 22-25, 30) ---
    def _run_gate(label: str, findings) -> None:
        blocked = False
        for fd in findings:
            if fd.severity == "error":
                log(f"ERROR: {label} [{fd.beat}]: {fd.message}")
                blocked = True
            else:
                log(f"{label} [{fd.beat}]: {fd.message}")
        if blocked:
            raise typer.Exit(code=1)

    from automap import cutscenes as cutscenes_mod
    from automap import economy as economy_mod
    from automap import items as items_mod
    from automap import ui_gate as ui_mod
    if (src_root / "items").exists():
        _run_gate("items", items_mod.check_items(src_root))
    if (src_root / "skills").exists():
        _run_gate("skills", items_mod.check_skills(src_root))
    if (src_root / "classes").exists():
        from automap import classes as classes_mod
        _run_gate("classes", classes_mod.check_classes(src_root))
    # sequences (Story Director's tier): gate = contradictions block,
    # to-author warnings inform; then publish to content/sequences/ for the
    # SequenceRunner (NS1). The state ledger's runtime substrate is
    # WorldState, so the doc travels whole.
    from automap import sequences as sequences_mod
    seq_src = src_root / "story" / "sequences"
    seq_files = sorted(seq_src.glob("*.json")) if seq_src.exists() else []
    if seq_files:
        seq_findings = sequences_mod.check_all(src_root)
        seq_errs = [f for f in seq_findings if f.severity == "error"]
        for f in seq_errs:
            log(f"ERROR: sequence [{f.beat}]: {f.message}")
        n_warn = len(seq_findings) - len(seq_errs)
        if seq_errs:
            raise typer.Exit(code=1)
        dst = content / "sequences"
        _publish_dir_reset(dst)
        for f in seq_files:
            shutil.copy2(f, dst / f.name)
            manifest["artifacts"].setdefault("sequences", []).append(
                {"name": f.name, "sha256_12": _sha12(f)})
        log(f"sequences: {len(seq_files)} published, {n_warn} to-author "
            "warnings (the checklist)")

    for kind, gate in (("economy", economy_mod.check_economy),
                       ("ui", ui_mod.check_ui),
                       ("cutscenes", cutscenes_mod.check_all)):
        src = src_root / kind
        docs = sorted(src.glob("*.json")) if src.exists() else []
        if not docs:
            continue
        for f in docs:
            _validate(kind, f, log)  # schema warns if absent
        _run_gate(kind, gate(src_root))
        dst = content / kind
        _publish_dir_reset(dst)
        for f in docs:
            shutil.copy2(f, dst / f.name)
            manifest["artifacts"].setdefault(kind, []).append(
                {"name": f.name, "sha256_12": _sha12(f)})
        log(f"{kind}: {len(docs)} doc(s) gated + published")

    # --- portraits: staged figure faces -> content/portraits/<slug>.png ---
    portraits_src = root / "work" / "game" / game / "portraits"
    portraits = sorted(portraits_src.glob("*.png")) if portraits_src.exists() else []
    if portraits:
        dst = content / "portraits"
        _publish_dir_reset(dst)
        for p in portraits:
            shutil.copy2(p, dst / p.name)
            manifest["artifacts"].setdefault("portraits", []).append(
                {"name": p.name, "sha256_12": _sha12(p)})
        log(f"portraits: {len(portraits)} published")
    for kind in JSON_KINDS:
        src = src_root / kind
        if not src.exists():
            continue
        dst = content / kind
        _publish_dir_reset(dst)
        for f in _json_files(src):
            shutil.copy2(f, dst / f.name)
            manifest["artifacts"].setdefault(kind, []).append(
                {"name": f.name, "sha256_12": _sha12(f)})

    # --- binary assets pulled from the reference repo per assets.json ---
    assets_doc = src_root / "assets.json"
    if assets_doc.exists():
        spec = json.loads(assets_doc.read_text())
        ref = Path(spec["reference_root"]).expanduser()
        dst = content / "backgrounds"
        _publish_dir_reset(dst)
        for rel in spec.get("backgrounds", []):
            p = ref / rel
            shutil.copy2(p, dst / p.name)
            manifest["artifacts"].setdefault("backgrounds", []).append(
                {"name": p.name, "sha256_12": _sha12(p), "source": rel})
        log(f"backgrounds: {len(spec.get('backgrounds', []))} pulled from reference")

        # game-owned backgrounds (generated, not from the reference game) —
        # e.g. the Weirgate battle backdrop; they add to / override the pulled
        # set by filename
        game_bg = sorted((src_root / "backgrounds").glob("*.png")) \
            if (src_root / "backgrounds").exists() else []
        for p in game_bg:
            shutil.copy2(p, dst / p.name)
            manifest["artifacts"].setdefault("backgrounds", []).append(
                {"name": p.name, "sha256_12": _sha12(p), "source": "game"})
        if game_bg:
            log(f"backgrounds: {len(game_bg)} game-owned")

        cdst = content / "creatures"
        cdst.mkdir(parents=True, exist_ok=True)
        for c in spec.get("creature_sprites", []):
            slug, fps = c["slug"], c.get("fps", 8)  # int, or per-anim dict
            _publish_dir_reset(cdst / slug)  # per-slug: creature JSON docs share this tree
            # generated people live in THIS repo (npc_creator stages them
            # under work/); reference people come from the reference repo
            frames_src = (root / c["frames_dir"]) if c.get("local") \
                else ref / c["frames_dir"]
            anims: dict[str, dict] = {}
            for anim_dir in sorted(p for p in frames_src.iterdir() if p.is_dir()):
                frames = sorted(f.name for f in anim_dir.iterdir()
                                if f.suffix.lower() in (".png", ".webp", ".jpg", ".jpeg"))
                if not frames:
                    continue
                out = cdst / slug / "frames" / anim_dir.name
                out.mkdir(parents=True)
                for fn in frames:
                    shutil.copy2(anim_dir / fn, out / fn)
                anim_fps = (fps.get(anim_dir.name, 8)
                            if isinstance(fps, dict) else int(fps))
                # a collapse (Faint/Hurt) plays ONCE and holds; everything else
                # loops. The engine reads this (creature_sprites honors `loop`).
                loop = not anim_dir.name.split("_")[0] in ("Faint", "Hurt")
                anims[anim_dir.name] = {"fps": anim_fps, "loop": loop,
                                        "frames": frames}
            # the manifest the runtime actually READS (unlike the original's) —
            # frames listed in play order, fps explicit, loop by convention
            (cdst / slug / "manifest.json").write_text(json.dumps(
                {"slug": slug, "animations": anims}, indent=2) + "\n")
            manifest["artifacts"].setdefault("creatures", []).append(
                {"name": slug, "animations": len(anims)})
            log(f"creature '{slug}': {len(anims)} animation(s) + manifest")

    # --- the curated ULPC layer catalog (the in-game character creator) ---
    ulpc_src = root / "work" / "game" / game / "ulpc"
    if (ulpc_src / "catalog.json").exists():
        ulpc_dst = content / "ulpc"
        _publish_dir_reset(ulpc_dst)
        n = 0
        for f in ulpc_src.rglob("*"):
            if f.is_file():
                rel = f.relative_to(ulpc_src)
                (ulpc_dst / rel).parent.mkdir(parents=True, exist_ok=True)
                shutil.copy2(f, ulpc_dst / rel)
                n += 1 if f.suffix == ".png" else 0
        manifest["artifacts"]["ulpc"] = [{"sheets": n}]
        log(f"ulpc catalog: {n} layer sheets + catalog.json")

    # --- the game-design document (the gspec: rules as data) ---
    design = src_root / "design.json"
    if design.exists():
        try:
            import platform_specs
            gd_versions = sorted(
                (Path(platform_specs.__file__).parent.parent / "schemas"
                 / "game-design").glob("*.json"))
            gd_latest = gd_versions[-1].stem
            platform_specs.validate(json.loads(design.read_text()),
                                    "game-design", gd_latest)
            log(f"design.json valid (game-design@{gd_latest})")
        except ImportError:
            log("WARNING: platform-specs not installed - design.json NOT validated")
        shutil.copy2(design, content / "design.json")
        manifest["artifacts"]["design"] = [{"name": "design.json", "sha256_12": _sha12(design)}]

    props_src = root / "work" / "game" / game / "props"
    if props_src.exists():
        dst = content / "props"
        dst.mkdir(parents=True, exist_ok=True)
        # touch-up guard: a file in the game repo that differs from its LAST
        # PUBLISHED hash was hand-edited — never overwrite it
        prev_hashes: dict = {}
        prev_manifest_path = content / "manifest.json"
        if prev_manifest_path.exists():
            for e in json.loads(prev_manifest_path.read_text()).get(
                    "artifacts", {}).get("props", []):
                prev_hashes[e["name"]] = e.get("sha256_12")
        manual: set = set()
        published = 0
        for f in sorted(props_src.iterdir()):
            if f.suffix.lower() != ".png" or f.stem.startswith("preview"):
                continue
            dest = dst / f.name
            if dest.exists():
                dest_hash = _sha12(dest)
                last = prev_hashes.get(f.name)
                if last is not None and dest_hash != last:
                    manual.add(f.name)
                    log(f"props: '{f.name}' hand-edited in the game repo — "
                        "PRESERVED (provenance: manual)")
                    manifest["artifacts"].setdefault("props", []).append(
                        {"name": f.name, "sha256_12": dest_hash,
                         "provenance": "manual"})
                    continue
            shutil.copy2(f, dest)
            manifest["artifacts"].setdefault("props", []).append(
                {"name": f.name, "sha256_12": _sha12(f)})
            published += 1
        # catalog: staged entries win EXCEPT manual files keep their entry,
        # flipped to provenance manual so resolvers count them as fitting
        staged_cat_path = props_src / "props.json"
        live_cat_path = dst / "props.json"
        if staged_cat_path.exists():
            staged_cat = json.loads(staged_cat_path.read_text())
            live_cat = json.loads(live_cat_path.read_text()) \
                if live_cat_path.exists() else {"props": {}}
            merged = dict(staged_cat)
            merged_props = dict(staged_cat.get("props", {}))
            for name, entry in live_cat.get("props", {}).items():
                if entry.get("file") in manual or name + ".png" in manual:
                    entry = dict(entry, provenance="manual")
                    merged_props[name] = entry
            merged["props"] = merged_props
            live_cat_path.write_text(json.dumps(merged, indent=2) + "\n")
        log(f"props: {published} published, {len(manual)} hand-edit(s) preserved")
        # pack each tile-family atlas FROM the published (touch-up-inclusive)
        # sprites into the tilesets staging dir — the tilesets block below
        # publishes them; the baker builds one paintable TileSet per family
        try:
            sys.path.insert(0, str(root))
            from automap.asset_creator import pack_prop_atlas, tileset_families
            merged_now = json.loads(live_cat_path.read_text()) \
                if live_cat_path.exists() else {"props": {}}
            tstage = root / "work" / "game" / game / "tilesets"
            tstage.mkdir(parents=True, exist_ok=True)
            for stale in tstage.glob("*.trees.json"):  # pre-2.0 meta name
                stale.unlink()
            for family in tileset_families():
                atlas_img, atlas_meta = pack_prop_atlas(dst, merged_now, family)
                base = f"{game}_{family}s"
                if atlas_img is None:
                    for f in (tstage / f"{base}.png", tstage / f"{base}.tiles.json"):
                        f.unlink(missing_ok=True)
                    continue
                atlas_img.save(tstage / f"{base}.png")
                (tstage / f"{base}.tiles.json").write_text(
                    json.dumps(atlas_meta, indent=2) + "\n")
                log(f"{family} tileset: {len(atlas_meta['tiles'])} tiles "
                    "packed (paintable in the editor)")
        except Exception as e:
            log(f"WARNING: prop tileset packing failed: {e}")

    # --- generated tilesets (ground tilesets + the prop atlases packed just
    # above — this block must run AFTER the pack, or the published atlases
    # trail the catalog by one publish) ---
    tiles_src = root / "work" / "game" / game / "tilesets"
    if tiles_src.exists():
        dst = content / "tilesets"
        _publish_dir_reset(dst)
        published = 0
        for f in sorted(tiles_src.iterdir()):
            if f.suffix.lower() not in (".png", ".json") or f.stem.startswith("preview"):
                continue
            shutil.copy2(f, dst / f.name)
            manifest["artifacts"].setdefault("tilesets", []).append(
                {"name": f.name, "sha256_12": _sha12(f)})
            published += 1
        log(f"tilesets: {published} published (ground sets + prop atlases)")

    palette_src = root / "work" / "game" / game / "palette"
    if palette_src.exists():
        pdst = content / "palette"
        _publish_dir_reset(pdst)
        for f in sorted(palette_src.iterdir()):
            if f.suffix.lower() in (".png", ".json"):
                shutil.copy2(f, pdst / f.name)
                manifest["artifacts"].setdefault("palette", []).append(
                    {"name": f.name, "sha256_12": _sha12(f)})
        log("palette: published (color-pick from content/palette/palette.png)")

    (content / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")
    n = sum(len(v) for v in manifest["artifacts"].values())
    log(f"published {n} artifact(s) -> {content}")


if __name__ == "__main__":
    app()
