#!/usr/bin/env python
"""Casting Director / NPC Director / NPC Creator CLI — the casting chain's doors.

Commands:
  book    --game <g>                       cast-book + sheet status
  check   <level> --game <g>               the populate gate on one sheet
  npc create <slug> ...                    creature doc (stats balanced) + canon note
  npc request <slug> --look "..."          figure sprite request (genlab twin)
  npc generate <slug>                      fill the request from the image API
  npc ingest <slug>                        repixel the reference -> staged Idle frames
                                           + assets.json registration

Owned documents: games/<g>/casting/ (cast-book.md + <level>.json sheets);
charters in docs/studio-org.md (ledger rows 7–10). Sprites stage under
work/game/<g>/creatures_px/ and publish through stage 12 like reference
people.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import typer

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from automap import casting, npc_creator, story  # noqa: E402

app = typer.Typer(add_completion=False)
npc_app = typer.Typer(add_completion=False)
app.add_typer(npc_app, name="npc")

ROOT = Path(__file__).resolve().parent.parent
IDENTITY_DEFAULT = "identities/vaporis.json"


def _game_dir(game: str) -> Path:
    d = ROOT / "games" / game
    if not d.exists():
        typer.echo(f"no such game: {d}")
        raise typer.Exit(2)
    return d


def _identity(path_str: str) -> dict:
    return json.loads((ROOT / path_str).read_text())


def _npc_requests_dir(game: str) -> Path:
    return ROOT / "work" / "game" / game / "npc_requests"


def _frames_root(game: str) -> Path:
    return ROOT / "work" / "game" / game / "creatures_px"


@app.command()
def book(game: str = typer.Option("entropy")) -> None:
    """Cast-book pointer + per-sheet gate status."""
    gdir = _game_dir(game)
    book_md = casting.casting_dir(gdir) / "cast-book.md"
    typer.echo(f"cast book: {book_md if book_md.exists() else 'MISSING'}")
    for level_id in casting.list_sheets(gdir):
        sheet = casting.load_sheet(gdir, level_id)
        findings = casting.check_sheet(gdir, sheet)
        errs = [f for f in findings if f.severity == "error"]
        typer.echo(f"  {level_id:20s} npcs={len(sheet.get('npcs', []))} "
                   f"gate={'BLOCKED' if errs else 'ok'} "
                   f"({len(errs)} errors, {len(findings) - len(errs)} warnings)")


@app.command()
def library(game: str = typer.Option("entropy")) -> None:
    """The character library — casting/library.md + a contact sheet of
    every staged/published figure (the asset library's sibling)."""
    from PIL import Image

    gdir = _game_dir(game)
    creatures = casting.creature_ids(gdir)
    frames_root = _frames_root(game)
    lines = ["# Character library — who has a face\n",
             "Generated by `15 library`; consult BEFORE creating a person "
             "(reuse/share sprites first — casting sheets may point any "
             "background creature at any published sprite).\n",
             "| creature | name | archetype | region | sprite frames |",
             "|---|---|---|---|---|"]
    cells: list[tuple[str, Image.Image]] = []
    for slug, doc in sorted(creatures.items()):
        frames: list[Path] = []
        for anim in ("Idle_front", "Idle"):  # ulpc stages facings; figure_px doesn't
            frame_dir = frames_root / slug / anim
            if frame_dir.exists():
                frames = sorted(frame_dir.glob("*.png"))
                break
        src = f"staged ×{len(frames)}" if frames else \
            ("reference repo" if not doc.get("persona", {}).get("region")
             else "MISSING")
        lines.append(f"| {slug} | {doc.get('name', '')} | "
                     f"{doc.get('archetype', '')} | "
                     f"{doc.get('persona', {}).get('region', 'originals')} | "
                     f"{src} |")
        if frames:
            cells.append((slug, Image.open(frames[0])))
    (casting.casting_dir(gdir) / "library.md").write_text(
        "\n".join(lines) + "\n")
    if cells:
        scale, pad, label_h = 2, 12, 14
        w = max(im.width for _, im in cells) * scale
        h = max(im.height for _, im in cells) * scale
        cols = min(8, len(cells))
        rows = (len(cells) + cols - 1) // cols
        sheet = Image.new("RGBA", (cols * (w + pad) + pad,
                                   rows * (h + pad + label_h) + pad),
                          (46, 46, 50, 255))
        for i, (slug, im) in enumerate(cells):
            big = im.resize((im.width * scale, im.height * scale),
                            Image.NEAREST)
            x = pad + (i % cols) * (w + pad)
            y = pad + (i // cols) * (h + pad + label_h)
            sheet.paste(big, (x + (w - big.width) // 2, y), big)
        out = ROOT / "work" / "game" / game / "library" / "characters.png"
        out.parent.mkdir(parents=True, exist_ok=True)
        sheet.save(out)
        typer.echo(f"contact sheet: {out.relative_to(ROOT)}")
    typer.echo(f"library: games/{game}/casting/library.md "
               f"({len(creatures)} creatures, {len(cells)} with staged faces)")


@app.command()
def check(level: str, game: str = typer.Option("entropy")) -> None:
    """The populate gate on one casting sheet."""
    gdir = _game_dir(game)
    findings = casting.check_sheet(gdir, casting.load_sheet(gdir, level))
    for f in findings:
        typer.echo(f"  {f.severity.upper():5s} [{f.beat}] {f.message}")
    errs = [f for f in findings if f.severity == "error"]
    if errs:
        typer.echo(f"BLOCKED — {len(errs)} errors")
        raise typer.Exit(1)
    typer.echo("gate passed")


@npc_app.command()
def create(slug: str,
           name: str = typer.Option(...),
           archetype: str = typer.Option(...),
           region: str = typer.Option("vaporis"),
           home: str = typer.Option("foire_vaporum"),
           faction: str = typer.Option("the_order"),
           game: str = typer.Option("entropy")) -> None:
    """Creature document with archetype-balanced stats (creature@)."""
    if archetype not in npc_creator.ARCHETYPE_STATS:
        typer.echo(f"archetype must be one of "
                   f"{sorted(npc_creator.ARCHETYPE_STATS)}")
        raise typer.Exit(2)
    out = npc_creator.write_creature(_game_dir(game), slug, name, archetype,
                                     region, home, faction)
    stats = json.loads(out.read_text())["stats"]
    typer.echo(f"{out.relative_to(ROOT)} (total {sum(stats.values())})")


@npc_app.command()
def request(slug: str,
            look: str = typer.Option(..., help="who this person is, visually"),
            identity: str = typer.Option(IDENTITY_DEFAULT),
            game: str = typer.Option("entropy")) -> None:
    req = npc_creator.create_figure_request(
        _npc_requests_dir(game), _identity(identity), identity, slug, look)
    typer.echo(f"request: {req}")


def _latest_request(game: str, slug: str) -> Path:
    hits = sorted(_npc_requests_dir(game).glob(f"{slug}_r*"))
    if not hits:
        typer.echo(f"no figure request for '{slug}' — run `npc request` first")
        raise typer.Exit(2)
    return hits[-1]


@npc_app.command()
def generate(slug: str, count: int = typer.Option(1),
             game: str = typer.Option("entropy")) -> None:
    npc_creator.generate_figure(_latest_request(game, slug), count,
                                log=typer.echo)


@npc_app.command()
def compose(slug: str, game: str = typer.Option("entropy")) -> None:
    """ULPC channel: compose the committed build spec into engine-named,
    fully animated frames + assets.json registration (per-anim fps).

    The build spec lives at games/<g>/casting/builds/<slug>.ulpc.json —
    committed recipe, staged pixels (docs/explorations/
    ulpc-casting-integration.md)."""
    gdir = _game_dir(game)
    build = casting.casting_dir(gdir) / "builds" / f"{slug}.ulpc.json"
    if not build.exists():
        typer.echo(f"no build spec at {build.relative_to(ROOT)}")
        raise typer.Exit(2)
    result = npc_creator.compose_ulpc(gdir, slug, build, _frames_root(game),
                                      log=typer.echo)
    frames_dir = str((_frames_root(game) / slug).relative_to(ROOT))
    npc_creator.register_sprite(gdir, slug, frames_dir,
                                npc_creator.ulpc_fps_map(result["animations"]))
    typer.echo(f"composed {slug}: {', '.join(result['animations'])} "
               "(publish to build the manifest)")


@npc_app.command()
def ingest(slug: str,
           identity: str = typer.Option(IDENTITY_DEFAULT),
           reference: Path = typer.Option(None),
           fps: int = typer.Option(4),
           height_frac: float = typer.Option(
               1.0, help="stature: 1.0 adult, ~0.68 child (canvas headroom)"),
           game: str = typer.Option("entropy")) -> None:
    """Reference -> repixel figure -> staged frames + assets.json entry."""
    gdir = _game_dir(game)
    out = npc_creator.ingest_figure(_latest_request(game, slug),
                                    _identity(identity), _frames_root(game),
                                    slug, reference, height_frac)
    frames_dir = str(out.parent.parent.relative_to(ROOT))
    npc_creator.register_sprite(gdir, slug, frames_dir, fps)
    typer.echo(f"staged {out.relative_to(ROOT)} + assets.json entry "
               f"(publish to build the manifest)")


if __name__ == "__main__":
    app()
